apiVersion: template.openshift.io/v1
kind: "Template"
metadata:
  name: csv-subscription-template
  annotations:
    description: "Template for creating subscription for e2e-olm test"
    tags: "e2e"
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
    name: olm-testing
    namespace: olm-test
  spec:
    source: openshift-olm-test
    sourceNamespace: olm-test
    name: ${CSV_NAME}
    startingCSV: ${STARTING_CSV}
    channel: ${CHANNEL}
parameters:
-
  description: 'name of the CSV to use for the subscription'
  name: CSV_NAME
  value: openshiftansibleservicebroker
-
  description: 'the starting CSV to use for the subscription'
  name: STARTING_CSV
  value: openshiftansibleservicebroker.v4.1.0
-
  description:
  name: CHANNEL
  value: stable
